version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - chroma
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/chroma/data
