version: "3.9"

services:
  langgraph:
    build: .
    ports:
      - "8124:8124"
    environment:
      LANGGRAPH_CONFIG: /app/langgraph.json
    command: [
      "langgraph",
      "server",
      "start",
      "--config",
      "/app/langgraph.json",
      "--host",
      "0.0.0.0",
      "--port",
      "8124"
    ]
    volumes:
      - ./data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
