version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:1.28.1
    environment:
      - DB=sqlite
    ports:
      - "7233:7233"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      TEMPORAL_HOST: temporal:7233
      TEMPORAL_NAMESPACE: default
    depends_on:
      - temporal
    ports:
      - "8124:8124"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      TEMPORAL_HOST: temporal:7233
      TEMPORAL_NAMESPACE: default
    depends_on:
      - temporal
