[project]
name = "resume-tailoring-api"
version = "1.0.0"
description = "AI-powered resume tailoring service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.116.2",
    "fastapi-cli==0.0.7",
    "uvicorn[standard]==0.34.0",
    "pydantic==2.10.3",
    "pydantic-settings==2.7.0",
    "openai==1.59.5",
    "anthropic==0.42.0",
    "langchain==0.3.14",
    "langchain-openai==0.2.13",
    "sentence-transformers==3.3.1",
    "redis==5.2.1",
    "sqlalchemy==2.0.36",
    "alembic==1.14.0",
    "pgvector==0.3.6",
    "asyncpg==0.30.0",
    "pypdf==5.1.0",
    "python-docx==1.1.2",
    "python-multipart==0.0.20",
    "prometheus-client==0.21.1",
    "structlog==24.4.0",
    "greenlet==3.1.1",
    "aiosqlite==0.20.0",
]

[tool.uv]
dev-dependencies = [
    "pytest==8.3.5",
    "pytest-asyncio==0.25.0",
    "pytest-cov==6.0.0",
    "httpx==0.28.1",
    "ruff==0.8.6",
    "mypy==1.14.0",
    "pre-commit==4.0.1",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "B", "UP", "C90", "RUF"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
