[project]
name = "resume-assistant"
version = "0.1.0"
description = "Production-ready AI resume tailoring service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.117.1",
    "instructor==1.11.3",
    "openai==1.108.2",
    "anthropic==0.68.0",
    "pydantic==2.10.0",
    "redis==6.4.0",
    "python-multipart==0.0.20",
    "langsmith==0.4.30",
    "tiktoken==0.8.0",
    "pyyaml==6.0.2",
    "pytest==8.4.2",
    "pytest-asyncio==0.24.0"
]

[project.optional-dependencies]
dev = [
    "fakeredis==2.31.3",
    "ruff==0.13.1",
    "mypy==1.13.0"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning"
]
pythonpath = ["."]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["F", "I"]

[tool.ruff.format]
preview = true

[tool.mypy]
python_version = "3.12"
strict = false
warn_unused_configs = true
ignore_missing_imports = true
