name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync --dev
      - name: Run Ruff
        run: uv run ruff check

  type-check:
    name: Mypy type check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync --dev
      - name: Run mypy
        run: uv run mypy app

  tests:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --dev
      - name: Run pytest
        run: uv run pytest
