name: CI

on:
  push:
    branches: [main]
  pull_request:


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    env:
      UV_PYTHON_VERSION: '3.12'
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ${{ env.HOME }}/.cache/uv
          key: ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-
      - name: Install dependencies
        run: uv sync --extra dev --locked
      - name: Run Ruff
        run: uv run --extra dev ruff check

  type-check:
    name: Mypy type check
    runs-on: ubuntu-latest
    env:
      UV_PYTHON_VERSION: '3.12'
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ${{ env.HOME }}/.cache/uv
          key: ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-
      - name: Install dependencies
        run: uv sync --extra dev --locked
      - name: Run mypy
        run: uv run --extra dev mypy app

  tests:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    env:
      UV_PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ${{ env.HOME }}/.cache/uv
          key: ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-
      - name: Install dependencies
        run: uv sync --extra dev --locked
      - name: Run pytest
        run: uv run pytest

