name: Generate OpenAPI schema

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'shared/api-types/**'

permissions:
  contents: write

env:
  UV_PYTHON_VERSION: '3.13'

jobs:
  openapi:
    name: Build OpenAPI schema
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.UV_PYTHON_VERSION }}

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            apps/backend/.venv
            ${{ env.HOME }}/.cache/uv
          key: ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-${{ hashFiles('apps/backend/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ env.UV_PYTHON_VERSION }}-

      - name: Install dependencies
        working-directory: apps/backend
        run: uv sync --frozen

      - name: Generate OpenAPI schema
        working-directory: apps/backend
        run: uv run python scripts/generate_openapi.py

      - name: Upload schema artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-schema
          path: shared/api-types/openapi.json
          if-no-files-found: error

      - name: Commit and push schema changes
        working-directory: .
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain shared/api-types/openapi.json | grep -q .; then
            git add shared/api-types/openapi.json
            git commit -m "chore: update OpenAPI schema"
            git push
          else
            echo "No schema changes to commit"
