name: release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --extra dev --locked

      - name: Run tests
        run: uv run pytest

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Semantic Release
        id: sr
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: img
        run: |
          owner=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          repo=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${owner}/${repo}" >> "$GITHUB_OUTPUT"

      - name: Build metadata
        id: meta
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Derive short SHA
        id: sha
        run: echo "SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute semver tags
        if: steps.sr.outputs.new_release_published == 'true'
        id: sv
        run: |
          VER="${{ steps.sr.outputs.new_release_version }}"
          echo "MAJOR=${VER%%.*}" >> $GITHUB_OUTPUT
          echo "MINOR=${VER%.*}" >> $GITHUB_OUTPUT

      - name: Build & push image
        if: steps.sr.outputs.new_release_published == 'true' && steps.sr.outputs.new_release_channel == ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sr.outputs.new_release_version }}
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sv.outputs.MINOR }}
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sv.outputs.MAJOR }}
            ${{ steps.img.outputs.IMAGE }}:latest
            ${{ steps.img.outputs.IMAGE }}:sha-${{ steps.sha.outputs.SHORT }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.NOW }}
            org.opencontainers.image.version=${{ steps.sr.outputs.new_release_version }}
            org.opencontainers.image.title=resume-assistant
            org.opencontainers.image.description=AI Resume Assistant powered by LangGraph
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}#readme
